// Generated by gencpp from file ball_detect/BoundingBox.msg
// DO NOT EDIT!


#ifndef BALL_DETECT_MESSAGE_BOUNDINGBOX_H
#define BALL_DETECT_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ball_detect
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , bbox_class()
    , confidence(0.0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , bbox_class(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _w_type;
  _w_type w;

   typedef float _h_type;
  _h_type h;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _bbox_class_type;
  _bbox_class_type bbox_class;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::ball_detect::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ball_detect::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::ball_detect::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::ball_detect::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::ball_detect::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ball_detect::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ball_detect::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ball_detect::BoundingBox_<ContainerAllocator1> & lhs, const ::ball_detect::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.bbox_class == rhs.bbox_class &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ball_detect::BoundingBox_<ContainerAllocator1> & lhs, const ::ball_detect::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ball_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ball_detect::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ball_detect::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ball_detect::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ball_detect::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_detect::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_detect::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ball_detect::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "951d96f0b69ae98de978cdaf0668263a";
  }

  static const char* value(const ::ball_detect::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x951d96f0b69ae98dULL;
  static const uint64_t static_value2 = 0xe978cdaf0668263aULL;
};

template<class ContainerAllocator>
struct DataType< ::ball_detect::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ball_detect/BoundingBox";
  }

  static const char* value(const ::ball_detect::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ball_detect::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 w\n"
"float32 h\n"
"string bbox_class\n"
"float32 confidence\n"
"\n"
"\n"
;
  }

  static const char* value(const ::ball_detect::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ball_detect::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.bbox_class);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ball_detect::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ball_detect::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
    s << indent << "bbox_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.bbox_class);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALL_DETECT_MESSAGE_BOUNDINGBOX_H
